### PR TITLE
adds information about content_height for scroll depth

### PR DESCRIPTION
**Pull request by lizzerdrix**
* adds information on scroll depth page about adding the content_height parameter to the __reach_config

### CODE REVIEW

**Comment by lizzerdrix** [comment]
@andremalan @h55nick @pnts a small change - let me know what you think!

**Comment by andremalan** [comment]
:+1:

**Comment by pnts** [comment]
I think we need to be stronger in our language - more definitive in what we want people to do. So in this case, "you should" or "it's important that you" instead of "you may want to". People don't know what decisions they should be making, so the more we can push them to what we want them to do, the better (imo). 

Other than that :+1:

**Comment by lizzerdrix** [comment]
@pnts changed! will merge & deploy unless anyone has any other comments

**Pull request merged**
