### PR TITLE
updates info on canonical URL

### PR DESCRIPTION
**Pull request by lizzerdrix**
* a quick update with finer details on the canonical URL, as it is the most frequent parameter that requires an in-depth explanation
* also, removes a bunch of whitespace

### CODE REVIEW

**Comment by h55nick** [comment]
death to all whitespace

**Comment by andremalan** [comment]
lgtm

**Comment by pnts** [comment]
Comments left. Otherwise, :+1:

**Comment by lizzerdrix** [comment]
@pnts updated! good to merge/push?

**Pull request merged**
